proxy:
  server:
    port: 7766
  admin:
    token: "jivhwe;12n;cha#;adf"
  aes:
    offset: xoeDOlsHE*3#f^a;
    secret: v8a;alu^hfKwnGJd
  jwt:
    secret: test
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/luqian_proxy?useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximumPoolSize: 10
      minimumIdle: 2
      idleTimeout: 300000
      connectionTimeout: 30000
      maxLifetime: 600000
luqian:
  inject: false
